stages:
    - deploy

pages:
  stage: deploy
  image: rust
  tags:
    - pages
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    MDBOOK_VERSION: 0.4.35
  before_script: |
    export PATH="$PATH:$CARGO_HOME/bin"
    cargo install --force --version ${MDBOOK_VERSION} mdbook 
    cargo install --force mdbook-external-links mdbook-linkcheck
  script:
    - mdbook build -d public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - public/html
  cache:
    paths:
      - $CARGO_HOME/bin
  